services:
  pgvector:
    image: 'pgvector/pgvector:pg16'
    environment:
      - 'POSTGRES_DB=java_rag_pdf'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_USER=postgres'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5595:5432'
#      frist er ta HOST port : second the container port.
